pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
  publish:
    image: plugins/docker
    repo: quay.io/hwuethrich/drone-with-nodejs
    registry: quay.io
    auto_tag: true
    secrets: [ docker_username, docker_password ]
