pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
  publish:
    image: plugins/docker
    repo: hwuethrich/drone-with-nodejs
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    dry_run: true # remove this
